#!/usr/bin/env bash
# bash script that transfert a file from local to a server

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -eq 3 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$1":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$1":~/
fi
