#!/usr/bin/env bash
# script that install Nginx on a server and when requesting /redirect_me it redirect
# to a page with "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo chmod 666 /etc/nginx/sites-available/default
file_to_config="/etc/nginx/sites-available/default"
block_in_file=$(mktemp)
echo -e "\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" >> "$block_in_file"
sudo sed -i "/^[[:space:]]*server {/r $block_in_file" "$file_to_config"
sudo rm "$block_in_file"
# after this changes u can reload the web server to see the changes using sudo service nginx reload
sudo ufw allow 'Nginx HTTP'
service nginx start
