#!/usr/bin/env bash
# script that install Nginx on a server and when requesting /redirect_me it redirect
# to a page with "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo chmod 666 /etc/nginx/sites-available/default
file_to_config="/etc/nginx/sites-available/default"
block_text="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "42i $block_text" "$file_to_config"
# after this changes u can reload the web server to see the changes using sudo service nginx reload
sudo ufw allow 'Nginx HTTP'
service nginx restart
