#!/usr/bin/bash
# Bash script to Configure the web1 and web2 + adding a custom Nginx response header to track
# which web server  is answering our HTTP requests


sudo apt-get update -y

sudo apt-get install -y nginx

sudo chmod 666 /var/www/html/index.nginx-debian.html

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default-backup

sudo chmod 666 /etc/nginx/sites-available/default

file_to_config="/etc/nginx/sites-available/default"

block_text="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo sed -i "42i $block_text" "$file_to_config"

sudo touch /var/www/html/404.html

sudo chmod 666 /var/www/html/404.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

text_in_file=$(mktemp)

echo -e "\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t}\n" >> "$text_in_file"

sudo sed -i "/listen 80 default_server/r $text_in_file" "$file_to_config"

sudo rm "$text_in_file"


block2_text="\\\tadd_header X-Served-By $(hostname);"

sudo sed -i "42i $block2_text" "$file_to_config"

sudo ufw allow 'Nginx HTTP'

sudo service nginx restart
