#!/usr/bin/env bash
# task 9 script

echo "$$" > /var/run/myscript.pid

function sigterm {

	echo "I hate the kill command"
	rm "/var/run/myscript.pid"
	exit
}

function sigint {

	echo "Y U no love me ?!"
	exit
}

function sigquit {

	rm "/var/run/myscript.pid"
	exit

}
	trap sigterm SIGTERM
	trap sigint SIGINT
	trap sigquit SIGQUIT


while true; do
	echo "To infinity and beyond"
	sleep 2
done
