#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# using while lopp + IFS
s_file="/etc/passwd"
while IFS=: read -r Username password user_id group_id user_info home_directory command
do
	echo "The user $Username is part of the $group_id gang, lives in $home_directory and rides $command. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
done<$s_file

