#!/usr/bin/env bash
# Bash script that displays bad luck for the 4 iter, good luck for 8 iter
# else Best School

i=1
while [[ $i -le 10 ]]
do
	if [ $i == 4 ]; then
		echo "bad luck"
	elif [ $i == 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i += 1))
done

