#!/usr/bin/env bash
# Bash script that gives you information about the school file
s_file="school"

if [ -e "$s_file" ]; then
	echo "school file exists"
	if [ -s "$s_file" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$s_file" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
